volumes:
  grafana-data:
    driver: local
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '3001:3001'
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
