openapi: 3.0.0
paths:
  /api/auth/register:
    post:
      operationId: AuthController_createUser
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegisterRequestDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRegisterResponseDto"
      tags: &a1
        - api/auth
  /api/auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginRequestDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserLoginResponseDto"
      tags: *a1
  /api/auth/password:
    post:
      operationId: AuthController_updatePassword
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdatePasswordRequestDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserUpdatePasswordResponseDto"
      tags: *a1
  /api/patients:
    get:
      operationId: PatientsController_fetchPatient
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - api/patients
      security:
        - bearer: []
  /metrics:
    get:
      operationId: PrometheusController_index
      parameters: []
      responses:
        "200":
          description: ""
info:
  title: Alter API
  description: API Documentation for Alter
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    UserRegisterRequestDto:
      type: object
      properties: {}
    UserRegisterResponseDto:
      type: object
      properties: {}
    UserLoginRequestDto:
      type: object
      properties: {}
    UserLoginResponseDto:
      type: object
      properties: {}
    UserUpdatePasswordRequestDto:
      type: object
      properties: {}
    UserUpdatePasswordResponseDto:
      type: object
      properties: {}
