name: CI

on:
  push:
    branches:
      - '*'

jobs:
  lint-format-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Check code formatting
        run: pnpm format --check

      - name: Start Redis
        run: docker-compose --file docker/redis/docker-compose.yaml up -d

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '6.0'
          mongodb-replica-set: test-rs
          mongodb-port: 27018

      - name: Run Prisma migrations
        env:
          MAIN_DATABASE_URI: ${{ secrets.MAIN_DATABASE_URI }}
        run: |
          pnpm prisma:generate:test
          pnpm prisma:push:test

      - name: Run tests
        run: pnpm test

      - name: Stop Docker containers
        run: |
          docker-compose --file docker/redis/docker-compose.yaml down
          docker-compose --file docker/mongodb/docker-compose.yaml down
